BEGIN;
CREATE SCHEMA IF NOT EXISTS zew;
REVOKE ALL ON SCHEMA zew FROM PUBLIC, anon, authenticated;
SET LOCAL search_path=zew,pg_catalog;
CREATE TABLE IF NOT EXISTS schema_migrations(name text PRIMARY KEY,executed_at text NOT NULL);
CREATE TABLE IF NOT EXISTS group_catalog(key text PRIMARY KEY,data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS planned_catalog(key text PRIMARY KEY,data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS workspaces(id text PRIMARY KEY,state jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(id text PRIMARY KEY,token_hash text NOT NULL UNIQUE,state jsonb NOT NULL DEFAULT '{}',expires_at bigint NOT NULL,workspace_id text NOT NULL REFERENCES workspaces(id));
CREATE INDEX IF NOT EXISTS sessions_workspace ON sessions(workspace_id);
CREATE TABLE IF NOT EXISTS accounts(id text PRIMARY KEY,email text NOT NULL,name text NOT NULL,workspace_id text NOT NULL UNIQUE REFERENCES workspaces(id));
CREATE TABLE IF NOT EXISTS driver_access(id text PRIMARY KEY,email text NOT NULL,user_id text UNIQUE,name text NOT NULL,vehicle text NOT NULL,seats integer NOT NULL CHECK(seats BETWEEN 1 AND 8),active integer NOT NULL DEFAULT 1 CHECK(active IN(0,1)));
CREATE UNIQUE INDEX IF NOT EXISTS driver_email ON driver_access(lower(email));
CREATE TABLE IF NOT EXISTS dispatch_settings(id integer PRIMARY KEY CHECK(id=1),test_driver_id text REFERENCES driver_access(id));
CREATE TABLE IF NOT EXISTS planned_departures(id text PRIMARY KEY,driver_id text NOT NULL REFERENCES driver_access(id),trip_id text NOT NULL,departure text NOT NULL,capacity integer NOT NULL CHECK(capacity BETWEEN 1 AND 8),status text NOT NULL DEFAULT 'open' CHECK(status IN('open','boarding','in_progress','completed')),UNIQUE(driver_id,trip_id,departure));
CREATE TABLE IF NOT EXISTS dispatch_requests(id text PRIMARY KEY,kind text NOT NULL CHECK(kind IN('circle','planned')),workspace_id text NOT NULL REFERENCES workspaces(id),driver_id text NOT NULL REFERENCES driver_access(id),status text NOT NULL,data jsonb NOT NULL,created_at text NOT NULL,updated_at text NOT NULL,departure_id text REFERENCES planned_departures(id));
CREATE INDEX IF NOT EXISTS dispatch_driver_status ON dispatch_requests(driver_id,status);
CREATE INDEX IF NOT EXISTS dispatch_departure_status ON dispatch_requests(departure_id,status);
CREATE TABLE IF NOT EXISTS events(id text PRIMARY KEY,session_id text NOT NULL,kind text NOT NULL,entity_id text NOT NULL,created_at text NOT NULL);
CREATE INDEX IF NOT EXISTS events_workspace ON events(session_id,created_at DESC);
CREATE TABLE IF NOT EXISTS dispatch_events(id text PRIMARY KEY,request_id text NOT NULL REFERENCES dispatch_requests(id),actor_id text NOT NULL,action text NOT NULL,created_at text NOT NULL);
CREATE TABLE IF NOT EXISTS mutation_receipts(workspace_id text NOT NULL REFERENCES workspaces(id),key text NOT NULL,fingerprint text NOT NULL,result jsonb NOT NULL,created_at bigint NOT NULL,PRIMARY KEY(workspace_id,key));
CREATE TABLE IF NOT EXISTS rate_limits(subject text PRIMARY KEY,count integer NOT NULL,expires_at bigint NOT NULL);
CREATE INDEX IF NOT EXISTS rate_limits_expiry ON rate_limits(expires_at);
CREATE TABLE IF NOT EXISTS booking_quotes(id text PRIMARY KEY,workspace_id text NOT NULL REFERENCES workspaces(id),snapshot jsonb NOT NULL,expires_at bigint NOT NULL,booking_id text);
CREATE INDEX IF NOT EXISTS booking_quotes_expiry ON booking_quotes(expires_at);
CREATE TABLE IF NOT EXISTS preview_settlements(request_id text PRIMARY KEY REFERENCES dispatch_requests(id),driver_id text NOT NULL REFERENCES driver_access(id),departure_id text REFERENCES planned_departures(id),gross_minor bigint NOT NULL CHECK(gross_minor>=0),fee_minor bigint NOT NULL CHECK(fee_minor>=0),payout_minor bigint NOT NULL CHECK(payout_minor>=0),currency text NOT NULL DEFAULT 'ETB' CHECK(currency='ETB'),simulated integer NOT NULL DEFAULT 1 CHECK(simulated=1),created_at text NOT NULL,CHECK(gross_minor=fee_minor+payout_minor));
CREATE OR REPLACE FUNCTION zew.immutable_settlement() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$ BEGIN RAISE EXCEPTION 'Preview settlements are append-only'; END; $$;
REVOKE ALL ON FUNCTION zew.immutable_settlement() FROM PUBLIC, anon, authenticated;
DROP TRIGGER IF EXISTS settlement_immutable ON preview_settlements;
CREATE TRIGGER settlement_immutable BEFORE UPDATE OR DELETE ON preview_settlements FOR EACH ROW EXECUTE FUNCTION zew.immutable_settlement();
CREATE TABLE IF NOT EXISTS request_metrics(minute bigint NOT NULL,route text NOT NULL,status integer NOT NULL,count integer NOT NULL,duration_ms double precision NOT NULL,PRIMARY KEY(minute,route,status));
CREATE TABLE IF NOT EXISTS operator_events(id text PRIMARY KEY,action text NOT NULL,affected integer NOT NULL,created_at text NOT NULL);
-- No application tables are exposed through Supabase's public Data API.
REVOKE ALL ON ALL TABLES IN SCHEMA zew FROM PUBLIC,anon,authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA zew FROM PUBLIC,anon,authenticated;
INSERT INTO schema_migrations VALUES ('001_schema', now()::text) ON CONFLICT DO NOTHING;
COMMIT;
